openapi: 3.1
info:
  title: Employee Management API
  description: API documentation for managing employees
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/employees:
    get:
      summary: Get all employees

    post:
      summary: Add a new employee

  /api/employees/{id}:
    get:
      summary: Get an employee by ID

    delete:
      summary: Delete an employee by ID

    patch:
      summary: Update an employee by ID
      description: Allows partial updates and does not need all the fields
      requestBody:
        content:
          application/json:
            example:
              name: John Doe
              phone: "1234567890"
              salary: 60000.00


components:
  schemas:
    Employee:
      type: object
      properties:
        emp_id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        department_id:
          type: integer
          example: 2
        phone:
          type: string
          example: 1234567890
        joining_date:
          type: string
          format: date
          example: 2023-01-01
        salary:
          type: number
          format: double
          example: 50000.5